#184948247 Configure ESLint and Git Pre-commit hook
atlp-rwanda/e-comm-team-amigos-fn pull request #10
Opened 2023-04-19 14:14 UTC by wilbrord2

What does this PR do?
This PR setup ESLint and Git Pre-commit hook

Description of Task to be completed?

- installing eslint 
- configure eslint for react 
- setting react rules

#### How should this be manually tested?
`npm run format`

What are the relevant pivotal tracker stories?
Story ID: [#184948247](https://www.pivotaltracker.com/story/show/184948247)

2023-04-19 19:32 UTC, Emile-SHUMBUSHO requested changes

2023-04-19 19:32 UTC, Emile-SHUMBUSHO commented on .eslintrc.json
> +  }
Remove an empty line from your codes

2023-04-19 19:32 UTC, Emile-SHUMBUSHO commented on .prettierrc.json
> +}
Remove an empty line from your codes

2023-04-19 19:32 UTC, Emile-SHUMBUSHO commented on package.json
> +    "format": "eslint --fix src/**/*.js"
Tried to test this on my local computer, but didn't find any find any results
<img width="1130" alt="Screenshot 2023-04-19 at 21 20 45" src="https://user-images.githubusercontent.com/49757277/233180048-96135dee-ec3c-4d3b-8cd8-cc6f15129060.png">

2023-04-19 19:32 UTC, Emile-SHUMBUSHO commented on package.json
> +      "npm run test"
using this `npm run test ` isn't going to bring a conflict with other test, such unit testing or they will work together? need more clarifications.

2023-04-19 22:07 UTC, wilbrord2 commented on .prettierrc.json
> +}
Done

2023-04-19 22:08 UTC, wilbrord2 commented on package.json
> +    "format": "eslint --fix src/**/*.js"
Try to declare a variable and don't use it you will get errors

2023-04-19 22:09 UTC, wilbrord2 commented on package.json
> +    "format": "eslint --fix src/**/*.js"
This is one if examples

2023-04-19 22:10 UTC, wilbrord2 commented on package.json
> +      "npm run test"
This mean that you can not run test as long as you still have errors and warning in your code 
So it Will not cause any conflicts

2023-04-20 08:20 UTC, Emile-SHUMBUSHO approved these changes

2023-04-20 11:52 UTC, AbdulKhaliq59 approved these changes

2023-04-20 13:22 UTC, khevin2 approved these changes

2023-04-24 13:24 UTC, Habinezajanvier approved these changes
👍

2023-04-24 13:25 UTC, merged