#184948242 Setup of unit testing in client
atlp-rwanda/e-comm-team-amigos-fn pull request #12
Opened 2023-04-19 14:32 UTC by Mystica52

**#184948242 Setup the unit test using jest on client**

**What does this PR do?**
have all setup of unit testing

**Description of Task to be completed?**
after cloning it and then 

- run npm init -y
- run "npm install jest react-script @testing-library/react @testing-library/jest-dom react-test-renderer
- run "npm install chai -- save-dev" for installation of chai
- then make sure that script for test in packege.json is react-script

How should this be manually tested?
for testing, use terminal and run "npm run test"

**Any background context you want to provide?**
there is implementation made in vs code with 3 folder src and components where there is app.js and tests folder where app.test.js include
**What are the relevant pivotal tracker/Trello stories?**
Story ID: [#184948242](https://www.pivotaltracker.com/story/show/184948242)

2023-04-19 19:39 UTC, Emile-SHUMBUSHO requested changes

2023-04-19 19:39 UTC, Emile-SHUMBUSHO commented on .circleci/config.yml
> +      - test
Remove an empty line from your codes

2023-04-19 21:11 UTC, khevin2 approved these changes

2023-04-20 11:46 UTC, AbdulKhaliq59 approved these changes

2023-04-20 11:48 UTC, AbdulKhaliq59 approved these changes
Rebase  unless it LGTM

2023-04-20 14:34 UTC, GasanaJr approved these changes

2023-04-20 14:38 UTC, GasanaJr commented on package.json
>      "dev": "webpack-dev-server --mode development",
add --exit to exit the testing after all tests are done

2023-04-20 14:40 UTC, GasanaJr requested changes
Tackle the comments I provided. Also do a passing test even if it's a mockup

2023-04-24 10:15 UTC, Habinezajanvier approved these changes
LGTM

2023-04-24 10:16 UTC, GasanaJr approved these changes

2023-04-24 10:16 UTC, merged