#184948248 Setup GitHub actions
atlp-rwanda/e-comm-team-amigos-fn pull request #13
Opened 2023-04-20 01:19 UTC by GasanaJr

#### What does this PR do?
This PR configures GitHub actions for continuous integration
#### Description of Task to be completed?
- configure GitHub actions
#### How should this be manually tested?
- clone this repo `git clone https://github.com/atlp-rwanda/e-comm-team-amigos-fn`
- switch your working directory `cd e-comm-team-amigos-fn`
- install all dependencies by running `npm install`
- make any relevant change and push
- the tests should run automatically after a push
#### Any background context you want to provide?
- Node JS installed in your local machine
#### What are the relevant pivotal tracker stories?
Story ID: [#184948248](https://www.pivotaltracker.com/story/show/184948248)

2023-04-20 06:01 UTC, Emile-SHUMBUSHO approved these changes

2023-04-20 11:27 UTC, AbdulKhaliq59 approved these changes

2023-04-20 14:10 UTC, khevin2 requested changes
Depending on PT board story, you should also add a badge on Readme.

2023-04-24 11:10 UTC, Habinezajanvier approved these changes
🥇

2023-04-24 11:27 UTC, merged