#184948254 implementing two factor Authentication
atlp-rwanda/e-comm-team-amigos-fn pull request #17
Opened 2023-04-25 13:35 UTC by wilbrord2

#### What does this PR do?
         This PR is for Authenticating user with a role of seller before login 
#### Description of Task to be completed?
- [ ]  Design layout of page in figma 
- [ ]  create 2FA page 
- [ ] validate form 
- [ ] integrating with Api
- [ ] testing 

#### How should this be manually tested?

-  In your project terminal, run git fetch origin pull/17/head:ft-two-factor-authentication-#184948254
- Checkout to ft-two-factor-authentication-#184948254 branch
- Install all the dependencies by running npm install
- Then run the project by typing npm run dev
- Navigate to `/authentication`

### routes to be tested
  `/authentication` 

#### What are the relevant pivotal tracker/Trello stories?
Story ID: [#184948254](https://www.pivotaltracker.com/story/show/184948254)

#### Screenshots (if appropriate)

2023-04-28 06:46 UTC, Emile-SHUMBUSHO commented on src/style.css
> +}/*# sourceMappingURL=style.css.map */
remove an empty line of of code

2023-04-28 06:46 UTC, Emile-SHUMBUSHO commented on src/components/Authentication.jsx
> +export default sellerAuth;
Remove an empty line of code

2023-04-28 06:46 UTC, Emile-SHUMBUSHO commented on src/assets/css/authentication.scss
> +  }
Remove an empty line of code

2023-04-28 06:46 UTC, Emile-SHUMBUSHO commented on src/assets/css/authentication.css
> +}/*# sourceMappingURL=authentication.css.map */
Remove an empty line of code

2023-04-28 06:48 UTC, Emile-SHUMBUSHO commented
This PR need some test and integration with API in order to test it's fully functionality

2023-04-28 12:48 UTC, GasanaJr requested changes
this looks nice. Add some unit tests

2023-04-28 21:57 UTC, Emile-SHUMBUSHO commented
Provide a screenshot of your passing tests

2023-05-05 12:44 UTC, GasanaJr approved these changes

2023-05-08 06:42 UTC, khevin2 approved these changes

2023-05-08 12:55 UTC, GasanaJr approved these changes

2023-05-08 21:57 UTC, Emile-SHUMBUSHO approved these changes

2023-05-09 04:03 UTC, ericndungutse approved these changes

2023-05-09 04:03 UTC, ericndungutse approved these changes

2023-05-09 04:03 UTC, ericndungutse approved these changes

2023-05-09 06:44 UTC, Habinezajanvier approved these changes
👍

2023-05-09 06:44 UTC, merged