# 184948252 log in using email and password
atlp-rwanda/e-comm-team-amigos-fn pull request #18
Opened 2023-04-25 17:26 UTC by Mystica52

**What does this PR do?**
This PR display the login page
**Description of Task to be completed?**
Have the following routers working
 `/login`
    user should be able to login with the valid email and password 
**How should this be manually tested?**
     - Checkout to ft-login-email-and-password-184948250 branch
     - Install all the dependencies by running npm install
     - Then run the project by typing npm start 
     - Navigate to /login route
**Routes to be tested:**
POST /login
**What are the relevant pivotal tracker/Trello stories?**
Story ID: [184948252](https://www.pivotaltracker.com/story/show/184948252)

2023-04-29 09:54 UTC, Emile-SHUMBUSHO commented
From screenShots of your design I can see that there is some inconsistency in your design, try to align input field, error messages, and buttons in the same margin.

2023-04-29 10:09 UTC, Emile-SHUMBUSHO requested changes

2023-04-29 10:09 UTC, Emile-SHUMBUSHO commented on src/redux/actions/action.js
> +});
Avoid empty line of code from your design and also align your cods in appropriate format.

2023-04-29 10:09 UTC, Emile-SHUMBUSHO commented on src/redux/actions/auth.js
> +};
Avoid empty Line from your codes

2023-04-29 10:09 UTC, Emile-SHUMBUSHO commented on src/views/login/LoginForm.jsx
> +    // router.push({pathname: "/success",query: values});
Avoid pushing commented codes on  a GitHub

2023-04-29 10:09 UTC, Emile-SHUMBUSHO commented on src/views/login/LoginForm.jsx
> +      // PrivateRoutes("/dashboard");
Commented code are not allowed to be pushed on a GitHub

2023-04-29 10:09 UTC, Emile-SHUMBUSHO commented on src/views/login/LoginForm.jsx
> +
Empty space in your code violates a code format criteria

2023-04-29 10:09 UTC, Emile-SHUMBUSHO commented on src/redux/store.js
> +
This codes performs the same functionality with codes from `reducer/store.js` please consider removing this file `rootReducer.js` and remain with `reducer/store.js`

2023-04-29 10:09 UTC, Emile-SHUMBUSHO commented on src/tests/login.test.js
> +// import React from "react";
Avoid commented code

2023-04-30 13:30 UTC, ericndungutse approved these changes

2023-05-01 08:15 UTC, Habinezajanvier requested changes

2023-05-01 08:15 UTC, Habinezajanvier commented on src/redux/actions/auth.js
> +          }
No need to push `console.log` in production code

2023-05-02 09:05 UTC, wilbrord2 requested changes
![Screenshot_20230502-110306](https://user-images.githubusercontent.com/79166151/235625609-9923ae8d-b22a-4e47-b44b-57804f420294.png)

Please change this error message color to white because they are not visible

2023-05-02 09:06 UTC, wilbrord2 commented
Please rebase and remove all conflicts

2023-05-02 12:07 UTC, wilbrord2 approved these changes

2023-05-02 13:13 UTC, AbdulKhaliq59 approved these changes

2023-05-02 13:17 UTC, GasanaJr approved these changes

2023-05-02 13:24 UTC, Emile-SHUMBUSHO approved these changes

2023-05-02 13:28 UTC, merged