#185027364 Create Landing Page of the app
atlp-rwanda/e-comm-team-amigos-fn pull request #21
Opened 2023-04-26 18:51 UTC by khevin2

### What does this PR do?
This PR add `Homepage` to the application.
### Description of Task to be completed?

- Add Navigation
- Add hero
- Create Footer

### How should this be manually tested?

- Clone this repo `git clone https://github.com/atlp-rwanda/e-comm-team-amigos-fn`
- Switch your working directory `cd e-comm-team-amigos-fn`
- Install all the dependencies by running `npm install`
- Then run the project by typing `npm start`

### Any background context you want to provide?

- Have Node Js installed in your local machine
- Have latest web browser

### What are the relevant pivotal tracker?

Story ID:  [#185027364](https://www.pivotaltracker.com/story/show/185027364)

### Screenshots

2023-04-29 09:09 UTC, Emile-SHUMBUSHO commented on jsconfig.json
> +}
Avoid an empty line from your code

2023-04-29 09:09 UTC, Emile-SHUMBUSHO commented on src/components/Button/Button.css
> +}
Avoid an empty line from your code

2023-04-29 09:09 UTC, Emile-SHUMBUSHO commented on src/components/Hero/Hero.css
> +}
Avoid an empty line from your code

2023-04-29 09:09 UTC, Emile-SHUMBUSHO commented on src/components/TodayDeal/style.css
> +}
Avoid an empty line from your code

2023-04-29 09:09 UTC, Emile-SHUMBUSHO commented on src/components/TopCategories/style.css
> +}
Avoid empty line from your code

2023-04-29 12:10 UTC, khevin2 commented on src/components/TopCategories/style.css
> +}
What do you mean by 'empty lines'?

2023-05-01 14:18 UTC, GasanaJr requested changes
Amazing Job, Khevin 🫡. However rebase and fix tests

2023-05-02 14:44 UTC, wilbrord2 requested changes
work on the slider, the responsiveness on big screen, and add some padding on some sections

2023-05-02 14:51 UTC, GasanaJr requested changes
The tests still have an issue bro

2023-05-02 14:54 UTC, GasanaJr commented on src/components/Hero/index.jsx
> +
Shouldn't it be `swiper.css` instead of `swiper/css`? Because the tests are failing because of this

2023-05-02 14:57 UTC, khevin2 commented on src/components/Hero/index.jsx
> +
It's actually `swiper/css`. and I'm searching for a way the tests could pass using this method

2023-05-04 06:45 UTC, Emile-SHUMBUSHO commented
Put some margin on cart, otherwise LGTM

<img width="301" alt="Screenshot 2023-05-04 at 08 42 58" src="https://user-images.githubusercontent.com/49757277/236129919-cdd203ff-4a6d-47c7-b7ea-001e09a4951f.png">

2023-05-04 14:58 UTC, AbdulKhaliq59 approved these changes
it LGTM

2023-05-04 18:19 UTC, Emile-SHUMBUSHO approved these changes

2023-05-05 06:14 UTC, GasanaJr approved these changes

2023-05-05 09:05 UTC, merged