#184948256 Update password every x amount of time
atlp-rwanda/e-comm-team-amigos-fn pull request #22
Opened 2023-04-26 20:25 UTC by Rwibutso

#### What does this PR do?
This PR  prompt an interface to user to change password for x amount of timet
#### Description of Task to be completed?
-  Create a UI for the task
- Code the functionality
- Integrate with the backend
- Test the application
#### How should this be manually tested?
- clone this repo `git clone https://github.com/atlp-rwanda/e-comm-team-amigos-fn`
- switch your working directory `cd e-comm-team-amigos-fn`
- create a `.env` and update it with `.env-example`
- install all dependencies by running `npm install`
- in your terminal, run `npm start`
#### Test the endpoints:
-  `/update-password`
#### Any background context you want to provide?
- Node JS installed
- Node server running
#### What are the relevant pivotal tracker stories?
Story ID: [#184948256](https://www.pivotaltracker.com/story/show/184948256)
####Screenshots
![Screenshot from 2023-04-28 12-14-22](https://user-images.githubusercontent.com/54440360/235121876-0e2e4c60-d8d1-40f7-b27f-fcacc13d2765.png)
![Screenshot from 2023-04-28 12-14-34](https://user-images.githubusercontent.com/54440360/235121904-a19b4229-3e3b-4ef2-96a6-8e33d6a2de61.png)

![Screenshot from 2023-05-02 14-19-09](https://user-images.githubusercontent.com/54440360/235664477-322993a1-3661-4ae5-86f4-d514dbbf941e.png)

2023-04-29 08:52 UTC, Emile-SHUMBUSHO commented
This PR has a conflict to resolve

2023-04-29 09:02 UTC, Emile-SHUMBUSHO requested changes

2023-04-29 09:02 UTC, Emile-SHUMBUSHO commented on src/assets/css/changePassword.css
> +}
Avoid an empty line from your code

2023-04-29 09:02 UTC, Emile-SHUMBUSHO commented on src/components/changePasswordForm.jsx
> +  export default ChangePasswordPage;
Avoid an empty line from your code

2023-04-29 09:02 UTC, Emile-SHUMBUSHO commented on src/views/changePasswordPage.jsx
> +}
Avoid an empty line from your code

2023-04-29 09:02 UTC, Emile-SHUMBUSHO commented on src/components/changePasswordForm.jsx
> +  });
Great Job for making integration with API but I'm suggesting to separate Formik validation and integration functionality. Further more, take advantage of using redux to manage states  in your component.

2023-05-04 11:39 UTC, AbdulKhaliq59 approved these changes
Rebase Unless it LGTM

2023-05-21 17:18 UTC, Emile-SHUMBUSHO approved these changes

2023-05-21 17:19 UTC, khevin2 approved these changes

2023-05-23 14:48 UTC, Habinezajanvier requested changes

2023-05-23 14:48 UTC, Habinezajanvier commented on src/views/updatePassword/updatePassword.style.scss
> +// }
Why is those commented codes, if they are not needed remove them at all

2023-05-23 17:11 UTC, Habinezajanvier approved these changes
👍

2023-05-23 17:11 UTC, merged