#184948257 view seller items in a collection
atlp-rwanda/e-comm-team-amigos-fn pull request #28
Opened 2023-05-04 11:33 UTC by Emile-SHUMBUSHO

What does this PR do?

This PR creates a functionality to allow user to view items  in the seller's collection

Description of Task to be completed?

- [ ] view a specific item in my collection
- [ ] view all items in my collection

How should this be manually tested?

- [ ] Clone this repo git clone https://github.com/atlp-rwanda/e-comm-team-amigos-fn
- [ ] Switch your working directory cd e-comm-team-amigos-fn
- [ ] Install all the dependencies by running npm install
- [ ] Then run the project by typing npm start

What are the relevant pivotal tracker/Trello stories?

[#184948257](https://www.pivotaltracker.com/n/projects/2639401/stories/184948257)

Screenshots (if appropriate)
<img width="1440" alt="Screenshot 2023-05-04 at 13 17 09" src="https://user-images.githubusercontent.com/49757277/236190245-46b3a6a9-efa7-495b-a035-74fa06af5241.png">

2023-05-05 12:50 UTC, GasanaJr reviewed
there is no  integration with the backend

2023-05-09 12:19 UTC, Rwibutso approved these changes

2023-05-09 12:38 UTC, 1MuhireDavid approved these changes

2023-05-09 12:39 UTC, AbdulKhaliq59 approved these changes

2023-05-09 12:39 UTC, AbdulKhaliq59 approved these changes

2023-05-09 14:08 UTC, GasanaJr requested changes
Fix conflicting files

2023-05-09 19:30 UTC, GasanaJr approved these changes

2023-05-09 19:30 UTC, GasanaJr approved these changes

2023-05-10 06:03 UTC, merged