#184948259 seller update product
atlp-rwanda/e-comm-team-amigos-fn pull request #31
Opened 2023-05-05 07:15 UTC by AbdulKhaliq59

#### What does this PR do?
This PR provide update existing product functionality in a collection of a seller
#### Description of Task to be completed?
 - [ ] update product functionality
 - [ ] Test update product functionality
#### How should this be manually tested?
- `dashboard/product`
- `dashboard/product/update-product`
#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?
 [#184948259](https://www.pivotaltracker.com/story/show/184948259)
#### Screenshots (if appropriate)
<img width="1440" alt="Screenshot 2023-05-05 at 09 12 23" src="https://user-images.githubusercontent.com/71641626/236397467-efde514a-f313-4826-9830-4a0585f88381.png">
#### Questions:

2023-05-11 18:43 UTC, GasanaJr requested changes
Fix the css for the main container.
<img width="1196" alt="Screenshot 2023-05-11 at 8 42 24 PM" src="https://github.com/atlp-rwanda/e-comm-team-amigos-fn/assets/43322242/7eee6d24-40ed-44ee-a032-eda312a8638a">
This is how it looks on my side.

2023-05-15 10:12 UTC, Emile-SHUMBUSHO approved these changes

2023-05-15 10:19 UTC, Habinezajanvier approved these changes
👍

2023-05-15 10:19 UTC, merged

2023-05-15 10:21 UTC, Mystica52 approved these changes
it is working correct. however when you clicked on the update button it shows that existing product instead of showing the updated one. but when you refresh page it show the exact. is there any way you can click on update then it  can show the updated one??