Ft delete seller product 184948260
atlp-rwanda/e-comm-team-amigos-fn pull request #32
Opened 2023-05-05 08:19 UTC by khevin2

### What does this PR do?
This PR add allows a `Merchant/vendor` to delete a product in his own collection
### Description of Task to be completed?
- Add a button to delete a product in products list
- Add confirm Modal before deleting
- Delete a product on the backend
### How should this be manually tested?
- Clone this repo `git clone https://github.com/atlp-rwanda/e-comm-team-amigos-fn`
- Switch your working directory `cd e-comm-team-amigos-fn`
- Install all the dependencies by running `npm install`
- Then run the project by typing `npm start`
### Any background context you want to provide?
- Have Node Js installed in your local machine
- Have latest web browser
### What are the relevant pivotal tracker?
Story ID:  [#184948260](https://www.pivotaltracker.com/story/show/184948260)
### Screenshots

2023-05-07 21:39 UTC, Emile-SHUMBUSHO commented on src/redux/actions/sellerCollection.actions.js
> +		'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmMmMzMDA3MC04MjQxLTQzYWEtYWY0YS04YmQwM2YzZDVkNjMiLCJ1c2VyRW1haWwiOiJjeXVzYS5raGV2ZW5Ab3V0bG9vay5jb20iLCJpYXQiOjE2ODM0NjEzNTEsImV4cCI6MTY4MzQ2NDk
Don't forget to replace this static token with dynamic one.

2023-05-07 21:40 UTC, Emile-SHUMBUSHO commented
Provide a screenshots for your UI implemented design

2023-05-08 14:41 UTC, GasanaJr reviewed
add some unit tests

2023-05-11 18:17 UTC, GasanaJr approved these changes
LGTM

2023-05-11 18:36 UTC, GasanaJr requested changes
I am facing some issues, I am deleting a product but it re-renders the product again. Look into what might be causing the behaviour

2023-05-12 12:38 UTC, wilbrord2 approved these changes

2023-05-12 12:38 UTC, wilbrord2 approved these changes

2023-05-12 12:45 UTC, GasanaJr requested changes
Rebase and resolve conflicts

2023-05-12 13:52 UTC, AbdulKhaliq59 approved these changes

2023-05-12 14:05 UTC, GasanaJr approved these changes

2023-05-15 11:01 UTC, Mystica52 approved these changes

2023-05-15 11:02 UTC, Mystica52 approved these changes
working correct unless rebase

2023-05-15 11:54 UTC, Emile-SHUMBUSHO commented
This PR has a conflict and won't be merged unless resolved.

2023-05-15 17:03 UTC, Habinezajanvier approved these changes
👍

2023-05-15 17:03 UTC, merged