#184948270 implementing add to cart
atlp-rwanda/e-comm-team-amigos-fn pull request #33
Opened 2023-05-08 07:45 UTC by wilbrord2

#### What does this PR do?
This PR is for buyer/seller add product to cart
#### Description of Task to be completed?
- Implement the designs in react
- Integrate with the backend
- Jest testing 
#### How should this be manually tested?
- clone this repo `git clone https://github.com/atlp-rwanda/e-comm-team-amigos-fn`
- switch your working directory `cd e-comm-team-amigos-fn`
- create an `.env` and update it with `.env-example`
- install all dependencies by running `npm install`
- in your terminal run `npm run dev`
- route to endpoint `/cart`
#### Screenshots
![Screenshot (191)](https://user-images.githubusercontent.com/79166151/236765555-0f5018f3-6e6d-422c-9d21-ee4710a6f362.png)

2023-05-18 11:42 UTC, GasanaJr requested changes
The test files are failing; some data might have been lost during rebasing. you can check on develop and fix them

2023-05-18 12:26 UTC, Emile-SHUMBUSHO commented
Align cart content at the center
<img width="1440" alt="Screenshot 2023-05-18 at 14 17 30" src="https://github.com/atlp-rwanda/e-comm-team-amigos-fn/assets/49757277/07135800-60a0-4d0f-be2a-85d1a73db2f0">

On successfully add to cart I'm suggesting to  redirect user to the cart  or somewhere else rather than staying on this UI otherwise this LGTM.
<img width="1440" alt="Screenshot 2023-05-18 at 14 18 34" src="https://github.com/atlp-rwanda/e-comm-team-amigos-fn/assets/49757277/d7e3c46d-263c-44d9-b3f4-3eb3bfa23d10">

2023-05-18 12:30 UTC, GasanaJr approved these changes
The functionality works perfectly fine. fix the unit tests and we are good to go

2023-05-18 13:03 UTC, Habinezajanvier requested changes

2023-05-18 13:03 UTC, Habinezajanvier commented on src/assets/css/Search.css
> +  margin-top: 20px;
Make sure that we are sticking to scss

2023-05-18 13:07 UTC, Habinezajanvier requested changes

2023-05-18 13:07 UTC, Habinezajanvier commented on src/assets/css/Search.css
> +  height: 200px;
Make sure that we are sticking to scss not css

2023-05-18 13:07 UTC, Habinezajanvier commented on src/assets/css/addToCart.css
> +    width: 90%;
SCSS please not vanilla css

2023-05-19 09:41 UTC, ericndungutse approved these changes

2023-05-19 09:41 UTC, ericndungutse approved these changes

2023-05-19 09:57 UTC, Mystica52 approved these changes
LGTM unless rebase

2023-05-19 12:49 UTC, Habinezajanvier approved these changes
👍

2023-05-19 12:49 UTC, merged