Ft recommended products 184948278
atlp-rwanda/e-comm-team-amigos-fn pull request #36
Opened 2023-05-16 14:48 UTC by GasanaJr

#### What does this PR do?
This PR adds recommended/similar products view on the front end.
#### Description of Task to be completed?
- adds similar items view on the front based on what product user searches  
#### How should this be manually tested?
- clone this repo `git clone https://github.com/atlp-rwanda/e-comm-team-amigos-fn`
- switch your working directory `cd e-comm-team-amigos-fn`
- create an `.env` and update it with `.env-example`
- install all dependencies by running `npm install`
- in your terminal run `npm start`
#### Any background context you want to provide?
- Node JS installed in your local machine
#### What are the relevant pivotal tracker stories?
Story ID: [#184948278](https://www.pivotaltracker.com/story/show/184948278)

2023-05-17 05:55 UTC, Emile-SHUMBUSHO commented on src/components/RelatedItems/related.scss
> +    //justify-content: center;
commented code should not be pushed to the remote repository

2023-05-17 08:52 UTC, GasanaJr commented on src/components/RelatedItems/related.scss
> +    //justify-content: center;
Thanks for the reminder bro. It is still a work in progress. I will remove them.

2023-05-18 06:57 UTC, Emile-SHUMBUSHO commented
Add some margin-bottom and add footer if it's possible
<img width="1419" alt="Screenshot 2023-05-18 at 08 52 16" src="https://github.com/atlp-rwanda/e-comm-team-amigos-fn/assets/49757277/bc72d045-598c-4c55-8b88-1f3bc380b972">

2023-05-18 07:20 UTC, Emile-SHUMBUSHO approved these changes

2023-05-18 08:00 UTC, AbdulKhaliq59 approved these changes
I think I may suggest two things:
-  to add border-radius on this card 
-  remove console.log()
and unless it `LGTM`
<img width="451" alt="Screenshot 2023-05-18 at 09 53 14" src="https://github.com/atlp-rwanda/e-comm-team-amigos-fn/assets/71641626/b1989667-28a4-4770-a29c-2e5021a74220">

2023-05-18 09:26 UTC, GasanaJr commented
> I think I may suggest two things:
> 
> * to add border-radius on this card
> * remove console.log()
>   and unless it `LGTM`
> 
> <img alt="Screenshot 2023-05-18 at 09 53 14" width="451" src="https://user-images.githubusercontent.com/71641626/239176995-b1989667-28a4-4770-a29c-2e5021a74220.png">

The issue is resolved now @AbdulKhaliq59

2023-05-18 12:15 UTC, Rwibutso approved these changes

2023-05-18 12:59 UTC, Habinezajanvier requested changes

2023-05-18 12:59 UTC, Habinezajanvier commented on src/components/Product.jsx
> +
Can we please make sure that we are handling request in redux actions

2023-05-18 12:59 UTC, Habinezajanvier commented on src/components/Product.jsx
> +									</>
Starting from line 73 till here can be wrapped in a array.map functionality hence reducing lines of codes

2023-05-19 07:47 UTC, Habinezajanvier approved these changes
👍

2023-05-19 07:49 UTC, merged