#184948243 Setup react Router
atlp-rwanda/e-comm-team-amigos-fn pull request #4
Opened 2023-04-16 20:55 UTC by khevin2

### What does this PR do?
This PR add React router dom to the application.
### Description of Task to be completed?

- Add React Router
- Configure Router
- Create dummy routes for `/` and `/login`

### How should this be manually tested?

- Clone this repo `git clone https://github.com/atlp-rwanda/e-comm-team-amigos-fn`
- Switch your working directory `cd e-comm-team-amigos-fn`
- Install all the dependencies by running `npm install`
- Then run the project by typing `npm start`

### Any background context you want to provide?

- Have Node Js installed in your local machine
- Have latest web browser

### What are the relevant pivotal tracker?

Story ID:  [#184948243](https://www.pivotaltracker.com/story/show/184948243)

### Screenshots (if appropriate)

2023-04-17 05:45 UTC, Rwibutso approved these changes

2023-04-17 06:12 UTC, wilbrord2 approved these changes

2023-04-17 09:38 UTC, GasanaJr approved these changes

2023-04-17 09:44 UTC, GasanaJr approved these changes

2023-04-17 11:24 UTC, Emile-SHUMBUSHO commented on src/App.css
> +} */
If this codes are not there to serve please remove it.

2023-04-18 08:42 UTC, Habinezajanvier requested changes

2023-04-18 08:42 UTC, Habinezajanvier commented on src/App.js
> +
If they are not being used, don't import them here

2023-04-18 08:48 UTC, Habinezajanvier approved these changes
👍

2023-04-18 08:58 UTC, merged