#184948272 Implement clear cart
atlp-rwanda/e-comm-team-amigos-fn pull request #41
Opened 2023-05-17 19:37 UTC by Mystica52

**What does this PR do?**
This PR implements clear cart

**Description of Task to be completed?**
buyers should clear their cart

**How should this be manually tested?**
 - Clone this repo git clone https://github.com/atlp-rwanda/e-comm-team-amigos-fn
 -  Switch your working directory cd e-comm-team-amigos-fn
 -  Create an .env file and update it with .env-example
 -  Install all the dependencies by running npm install
 -  Then run the project by typing npm run dev

**Any background context you want to provide?**
Have Node Js installed in your local machine
**What are the relevant pivotal tracker/Trello stories?**
Story ID: [#184948272](https://www.pivotaltracker.com/story/show/184948272)

2023-05-20 21:50 UTC, khevin2 approved these changes

2023-05-21 18:03 UTC, GasanaJr requested changes
Fix the issue with tests

2023-05-22 10:56 UTC, wilbrord2 approved these changes

2023-05-22 13:31 UTC, AbdulKhaliq59 approved these changes

2023-05-22 13:51 UTC, Emile-SHUMBUSHO reviewed
clear cart response seems to respond even if user have finished to clean up cart, it seems like responses are keeps persisting in the redux states. consider remove it once user done with the process, otherwise LGTM.

2023-05-22 20:19 UTC, Emile-SHUMBUSHO approved these changes

2023-05-23 14:46 UTC, Habinezajanvier approved these changes
👍

2023-05-23 14:57 UTC, merged