#185233189 Get all products
atlp-rwanda/e-comm-team-amigos-fn pull request #45
Opened 2023-05-23 12:38 UTC by khevin2

#### What does this PR do?
This PR add functionality to view a list of all products
#### Description of Task to be completed?
- Add all products page
- Add pagination
- Make page responsive
#### How should this be manually tested?
- Clone this repo `git clone https://github.com/atlp-rwanda/e-comm-team-amigos-fn`
- Switch your working directory `cd e-comm-team-amigos-fn`
- Install all the dependencies by running `npm install`
- Then run the project by typing `npm start`
- test the endpoint `/products/all` route

#### Any background context you want to provide?
- Have Node Js installed in your local machine
- Latest web browser

#### What are the relevant pivotal tracker/Trello stories?

Story ID: [#185233189](https://www.pivotaltracker.com/story/show/185233189)

2023-05-25 13:12 UTC, Rwibutso approved these changes

2023-05-26 08:00 UTC, AbdulKhaliq59 requested changes
LGTM

2023-05-26 12:00 UTC, ericndungutse approved these changes

2023-05-26 15:55 UTC, Mystica52 approved these changes

2023-05-29 10:50 UTC, AbdulKhaliq59 approved these changes

2023-05-31 07:41 UTC, wilbrord2 approved these changes

2023-05-31 08:42 UTC, merged