#185233328 Integrate Categories Section with Backend
atlp-rwanda/e-comm-team-amigos-fn pull request #46
Opened 2023-05-23 14:59 UTC by AbdulKhaliq59

#### What does this PR do?
This PR is used to integrate categories Section with backend
#### Description of Task to be completed?
- [x] Filter and display all categories that are in all products
- [x] Display that products related to category accordingly
- [x] Test the functionality with jest
#### How should this be manually tested?
- `run GET: /`
#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?
Story ID: [#185233328](https://www.pivotaltracker.com/story/show/185233328)
#### Screenshots (if appropriate)
![screencapture-localhost-3000-2023-05-25-10_29_33](https://github.com/atlp-rwanda/e-comm-team-amigos-fn/assets/71641626/3179dea0-a171-4994-bfc0-e94155a48593)

#### Questions:

2023-05-25 11:00 UTC, GasanaJr commented on src/components/TopCategories/index.jsx
> +					{
Fetching should be done in redux

2023-05-25 11:01 UTC, GasanaJr commented on src/components/TodayDeal/index.jsx
> +					category,
Fetching should be done in redux

2023-05-25 11:01 UTC, GasanaJr commented on src/components/TodayDeal/index.jsx
> +					{
Use redux

2023-05-25 11:01 UTC, GasanaJr requested changes
Address the comments I left

2023-05-25 11:38 UTC, khevin2 commented
Please use Env variable and replace those hard coded backed links

2023-05-26 07:17 UTC, Emile-SHUMBUSHO reviewed
When selecting categories, there should be a loading indicator to show a user that there is a fetching of data that is going on, otherwise you have did a great job.

2023-05-26 07:25 UTC, wilbrord2 approved these changes

2023-05-26 07:56 UTC, GasanaJr commented on src/redux/actions/homeAction.js
> +			console.log(uniqueCategories);
the console logs are not necessary here

2023-05-26 07:57 UTC, GasanaJr requested changes
address the comment I left

2023-05-26 08:24 UTC, ericndungutse approved these changes
LGTM

2023-05-26 08:28 UTC, Emile-SHUMBUSHO approved these changes

2023-05-26 08:48 UTC, GasanaJr approved these changes

2023-05-26 08:52 UTC, Habinezajanvier requested changes

2023-05-26 08:52 UTC, Habinezajanvier commented on src/components/TopCategories/index.jsx
> +					},
Make sure you are not fetching inside components

2023-05-26 10:45 UTC, Mystica52 approved these changes

2023-05-26 11:48 UTC, Habinezajanvier approved these changes
👍

2023-05-26 11:49 UTC, merged