#184948240 Setup Redux
atlp-rwanda/e-comm-team-amigos-fn pull request #7
Opened 2023-04-18 14:08 UTC by AbdulKhaliq59

#### What does this PR do?
This PR setting up Redux functionality
#### Description of Task to be completed?
 - [x] `Installing redux`
 - [ ] `setting up Store`
 - [ ] `Setting up Reducer`
#### How should this be manually tested?
- run `npm run dev`
#### Any background context you want to provide?
- `Initial React project`
#### What are the relevant pivotal tracker/Trello stories?
Story ID: [#184948240](https://www.pivotaltracker.com/story/show/184948240)
#### Screenshots (if appropriate)
N/A
#### Questions:

2023-04-18 16:25 UTC, Emile-SHUMBUSHO commented on src/redux/rootReducer.js
> +});
Well done but I would like to have some simple reducer, just to test the setup functionality.

2023-04-18 16:43 UTC, GasanaJr requested changes
rebase on develop, you have some conflicting files

2023-04-19 20:07 UTC, Emile-SHUMBUSHO approved these changes

2023-04-19 20:08 UTC, Emile-SHUMBUSHO commented
LGTM except this failing test from circleCI and semaphoric

2023-04-20 00:58 UTC, GasanaJr approved these changes

2023-04-20 14:12 UTC, khevin2 approved these changes

2023-04-24 14:42 UTC, nshutijonathan approved these changes
LGTM

2023-04-24 14:44 UTC, merged